### ISSUE TITLE
Home screen ads is still showing 

### ISSUE THREAD

**Issue by MuhammadBayiz** [Xposed-Modules-Repo/com.wovow.youtubehelper#4]
Ads in the home screen is still showing
![Screenshot_20220703-185403_YouTube](https://user-images.githubusercontent.com/63660736/177047505-9c027e1c-95c2-4f3b-85f4-84e7b3589d7d.png)
![Screenshot_20220703-185355_YouTube](https://user-images.githubusercontent.com/63660736/177047506-823cd269-cf24-4c69-ba98-cb7256609b49.png)
My device OS:
My device: Mi 9t (Redmi K20)
Android version: Android 12.1 (12L)
NOAdsBackgroundPlaybackYT Version: 8.0.0
YouTube version: 17.14.35
Here's a log from lsposed:
[modules_2022-07-03T18:39:43.161.log](https://github.com/Xposed-Modules-Repo/com.wovow.youtubehelper/files/9035099/modules_2022-07-03T18.39.43.161.log)

**Comment by ohyeah521** [comment]
This is because your Android system version is too high. In order to improve security, Google restricts the read and write permissions of apk on the sdcard, resulting in some functions being unavailable. There are 2 methods you can try, 1, downgrade the android system version to below 10; 2, use the command to install


adb shell
cd /sdcard/
su
setenforce 0
pm install --force-queryable    plugin.apk

**Comment by MuhammadBayiz** [comment]
Second method worked
I used termux and installed "android-tools" package and entered the above command and restarted the module and YT.
